version: '2'
services:
    web:
        build:
            context: .
            dockerfile: dev.dockerfile
        volumes:
            - "./src/{{ src }}:/run/service/src/{{ src }}"
            - "./media:/run/service/media"
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql:5.6
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE={{ src }}
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - "./nginx:/etc/nginx/conf.d"
            - "./media:/var/media"
        depends_on:
            - web

